version: "3"
services:
  rec:
    build:
      context: ./rec
      dockerfile: Dockerfile.rec
    ports:
      - "6545:6545"
    networks:
      - mynetwork
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - "rec"
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
